### PR TITLE
Added new rule to catch emails properly & removed email skip hack

### PR DESCRIPTION
**Pull request by lrrrs**
This new rule should catch almost every email address...

### CODE REVIEW

**Comment by Ruenzuo** [comment]
@lrrrs could you merge master into your branch? https://github.com/xing/XNGMarkdownParser/pull/21 should've updated the project settings.

**Comment by Ruenzuo** [comment]
Looks good :+1:

**Comment by JoachimK** [comment]
@gskbyte Do you remember what the original intention of not linking @xing.com/root/path was? It's a correct URL and *not* an email.

Does changing it here to be linked lead to any issues that we missed?

**Comment by gskbyte** [comment]
@JoachimK to be honest I don't know, I think it was just a bug

**Comment by gskbyte** [comment]
BTW +1 for improving the tests :)

**Pull request merged**
